### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DizzyG123**
Added to music theory pages; trying to find out how to properly do a pull request

### CODE REVIEW

**Comment by levinericzimmermann** [comment]
Thanks @kvitor123.

Unfortunately there is a space too much between the square bracket and the round bracket, it should be `[Music Theory for Musicians](https://www.music-theory-for-musicians.com/)` instead of `[Music Theory for Musicians] (https://www.music-theory-for-musicians.com/)`. With this space, the markdown code isn't correctly rendered as a link.

Once this is corrected, this looks fine to me.

**Comment by DizzyG123** [comment]
@levinericzimmermann Fixed the spacing. Can the code be rendered as a link now? Let me know if it doesn't work still.

**Comment by levinericzimmermann** [comment]
Thanks @kvitor123, it works now! Maybe just please squash your commits into one, as this is semantically only 1 change ("Add Music Theory for Musicians").

**Comment by DizzyG123** [comment]
Hey there, 

Thanks for letting me know. If this is good to go, does someone review it and approve whether or not it gets added in the main page? I was looking back at it and noticed that the website wasn't there. It could be because I'm not looking in the right place for the change, but just wanted to ask if I could know for future commits.

**Comment by noteflakes** [comment]
Hi, please put the new entry in the correct place in order to respect alphabetic ordering.

**Comment by DizzyG123** [comment]
Okay @noteflakes I can look into it today to put it in the correct place. Thanks for letting me know.

**Pull request closed without merging**
